version: "2"

services:
  vault_server:
    networks:
      - develop
    image: "cypherhat/vault-ethereum:latest"
    ports:
      - "9200:9200"
    volumes:
      - "./config:/home/vault/config:rw"
    user: 0:0
    entrypoint: /home/vault/config/entrypoint.sh
    restart: always
networks:
  develop:
    driver: bridge
